name: Run Benchmarks

on:
  push:
    branches:
      - main
    paths:
      - 'flexynesis/**'

jobs:
  run_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.9'

    - name: Cache Conda environment
      uses: actions/cache@v2
      with:
        path: ~/miniconda/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('spec-file.txt') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Create environment with dependencies
      shell: bash -l {0}
      run: |
        conda create --name my_env --file spec-file.txt
        conda activate my_env

    - name: Install my package from source
      shell: bash -l {0}
      run: |
        conda activate my_env
        python setup.py install

    - name: Cache dataset
      uses: actions/cache@v2
      with:
        path: dataset
        key: ${{ runner.os }}-dataset-${{ hashFiles('dataset.zip') }}
        restore-keys: |
          ${{ runner.os }}-dataset-

    - name: Download dataset
      run: |
        if [ ! -d "dataset" ]; then
            curl -L -o dataset.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset.tgz 
            tar -xzvf dataset.tgz
        fi

    - name: Run package
      shell: bash -l {0}
      run: |
        conda activate my_env
        flexynesis dataset DirectPred sample.yaml

