name: run_benchmarks

on:
  push:
    branches:
      - main

jobs:
  run_package:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies and my package
      shell: bash -l {0}
      run: |
        $CONDA/bin/conda create --name my_env --file spec-file.txt
        python setup.py install

    - name: Download dataset
      run: |
        curl -L -o dataset.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset.tgz 
        tar -xzvf dataset.tgz

    - name: Run benchmark script
      shell: bash -l {0}
      run: |
        $CONDA/bin/conda init bash 
        $CONDA/bin/conda activate my_env
        flexynesis dataset DirectPred sample.yaml
