name: Run Benchmarks

on:
  push:
    branches:
      - main
    paths:
      - 'flexynesis/**'
      - '.github/workflows/**'
      - './spec-file.txt'
      - './pyproject.toml'
      - './manifest.scm'
      - './guix.scm'

jobs:
  run_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.9'

    - name: Cache Conda environment
      uses: actions/cache@v2
      with:
        path: ~/miniconda/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('spec-file.txt') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Create environment with dependencies
      shell: bash -l {0}
      run: |
        conda create --name my_env --file spec-file.txt
        conda activate my_env

    - name: Install my package from source
      shell: bash -l {0}
      run: |
        conda activate my_env
        pip install -e .
    
    # NOTE: Install pytorch geometric via pip
    - name: Install pytorch-geometric
      shell: bash -l {0}
      run: |
        conda activate my_env
        pip install torch_geometric

    - name: Download dataset1
      run: |
        curl -L -o dataset1.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset1.tgz 
        tar -xzvf dataset1.tgz
        
    - name: Download dataset2
      run: |
        curl -L -o dataset2.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset2.tgz 
        tar -xzvf dataset2.tgz

    - name: Run DirectPred
      shell: bash -l {0}
      run: |
        conda activate my_env
        flexynesis --data_path dataset1 --model_class DirectPred --target_variables Erlotinib --batch_variables Crizotinib --fusion_type early --hpo_iter 1 --features_min 500 --features_top_percentile 20 --log_transform False --data_types gex,cnv --outdir . --prefix erlotinib_direct --early_stop_patience 10 --use_loss_weighting False
        
    - name: Run supervised_vae
      shell: bash -l {0}
      run: |
        conda activate my_env
        flexynesis --data_path dataset1 --model_class supervised_vae --target_variables Erlotinib,Crizotinib --fusion_type early --hpo_iter 1 --features_min 500 --features_top_percentile 20 --log_transform False --data_types gex,cnv --outdir . --prefix erlotinib_svae --early_stop_patience 10 --use_loss_weighting True

    - name: Run MultiTripletNetwork
      shell: bash -l {0}
      run: |
        conda activate my_env
        flexynesis --data_path dataset2 --model_class MultiTripletNetwork --target_variables y --fusion_type early --hpo_iter 1 --features_min 500 --features_top_percentile 20 --log_transform False --data_types gex,meth --outdir . --prefix msi_triplet 
