name: Check Models on MPS
on:
  push:
    branches:
      - main
    paths:
      - 'flexynesis/**'
      - '.github/workflows/**'
      - './pyproject.toml'
      - './dist/**'

jobs:
  run_package_mps:
    runs-on: macos-latest
    name: Test Models on Apple Silicon MPS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check CPU Type
        run: sysctl -n machdep.cpu.brand_string

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest torch pandas numpy

      - name: Install my package from wheel
        run: |
          pip install dist/flexynesis_mps-1.0.8-py3-none-any.whl

      - name: Check MPS Availability
        run: |
          python -c "import torch; print('MPS available:', torch.backends.mps.is_available())"

      - name: Download dataset1
        run: |
          curl -L -o dataset1.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset1.tgz 
          tar -xzvf dataset1.tgz

      - name: Download stringdb data
        run: |
          wget https://stringdb-downloads.org/download/protein.links.v12.0/9606.protein.links.v12.0.txt.gz
          gzip -cd 9606.protein.links.v12.0.txt.gz > dataset1/9606.protein.links.v12.0.txt
          wget https://stringdb-downloads.org/download/protein.aliases.v12.0/9606.protein.aliases.v12.0.txt.gz
          gzip -cd 9606.protein.aliases.v12.0.txt.gz > dataset1/9606.protein.aliases.v12.0.txt

      - name: Download dataset2
        run: |
          curl -L -o dataset2.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset2.tgz
          tar -xzvf dataset2.tgz

      - name: Download LGG_GBM_dataset
        run: |
          curl -L -o lgggbm_tcga_pub_processed.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/lgggbm_tcga_pub_processed.tgz
          tar -xzvf lgggbm_tcga_pub_processed.tgz

      - name: Run DirectPred on MPS
        run: |
          flexynesis --data_path dataset1 --model_class DirectPred --target_variables Erlotinib --fusion_type early --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types gex,cnv --outdir . --prefix erlotinib_direct_mps --early_stop_patience 3 --use_loss_weighting False

      - name: Run DirectPred_TestSurvival on MPS
        run: |
          flexynesis --data_path lgggbm_tcga_pub_processed --model_class DirectPred --target_variables STUDY --fusion_type intermediate --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types mut,cna --outdir . --prefix lgg_surv_mps --early_stop_patience 3 --use_loss_weighting False --surv_event_var OS_STATUS --surv_time_var OS_MONTHS

      - name: Run DirectPred_TestCovariates on MPS
        run: |
          flexynesis --data_path lgggbm_tcga_pub_processed --model_class DirectPred --target_variables STUDY --fusion_type intermediate --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types mut --outdir . --prefix lgg_surv_mps --early_stop_patience 3 --use_loss_weighting False --covariates BCR_STATUS

      - name: Run DirectPred_Test_Explainers on MPS
        run: |
          flexynesis --data_path lgggbm_tcga_pub_processed --model_class DirectPred --target_variables STUDY --fusion_type intermediate --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types mut --outdir . --prefix lgg_surv_mps --early_stop_patience 3 --use_loss_weighting False --feature_importance_method Both

      - name: Run supervised_vae on MPS
        run: |
          flexynesis --data_path dataset1 --model_class supervised_vae --target_variables Erlotinib,Crizotinib --fusion_type early --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types gex,cnv --outdir . --prefix erlotinib_svae_mps --early_stop_patience 3 --use_loss_weighting True

      - name: Run CrossModalPred on MPS
        run: |
          flexynesis --data_path dataset1 --model_class CrossModalPred --target_variables Erlotinib --fusion_type intermediate --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types gex,cnv --input_layers gex --output_layers cnv --outdir . --prefix erlotinib_crossmodal_mps --early_stop_patience 3 --use_loss_weighting True

      - name: Run MultiTripletNetwork on MPS
        run: |
          flexynesis --data_path dataset2 --model_class MultiTripletNetwork --target_variables y --fusion_type early --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types gex,meth --outdir . --prefix msi_triplet_mps --early_stop_patience 3

      - name: Run GNN on MPS
        run: |
          flexynesis --data_path dataset1 --model_class GNN --target_variables Erlotinib --fusion_type intermediate --hpo_iter 1 --features_top_percentile 10 --log_transform False --data_types gex --outdir . --prefix erlotinib_gnn_mps --early_stop_patience 3 --use_loss_weighting False --subsample 50
