name: MPS Tests on macOS

on:
  push:
    branches:
      - main
    paths:
      - "flexynesis/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/mps-test.yml"

  pull_request:
    paths:
      - "flexynesis/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/mps-test.yml"

jobs:
  mps-tests:
    name: Test MPS on Apple Silicon
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check CPU Type
      run: sysctl -n machdep.cpu.brand_string

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest torch pandas numpy

    - name: Install my package from wheel
      run: |
        pip install dist/flexynesis_mps-1.0.8-py3-none-any.whl

    - name: Check MPS Availability
      run: |
        python -c "import torch; print('MPS available:', torch.backends.mps.is_available())"

    - name: Run Unit Tests with MPS device
      run: |
        if [ -d "tests/unit" ]; then
          pytest -vvv --color=yes tests/unit -k "not slow"
        else
          echo "No unit tests directory found, skipping unit tests"
        fi