name: Check Tutorials

on:
  workflow_dispatch: # This line enables manual triggering of the workflow
  schedule:
    # Runs at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'

jobs:
  check_tutorials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache Python environment
      uses: actions/cache@v2
      with:
        path: ~/.venv  # Adjust path based on where you create your venv
        key: ${{ runner.os }}-venv-${{ hashFiles('pyproject.toml') }}  
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create virtual environment
      run: |
        python -m venv ~/.venv/my_env

    - name: Install my package from source
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        python -m pip install -e .
    
    - name: Install Jupyter Kernel
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        python -m ipykernel install --user --name my_env_kernel --display-name "my_env_kernel"

    - name: Compile brca_subtypes.ipynb
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        notebook='examples/tutorials/brca_subtypes'
        papermill "${notebook}.ipynb" "${notebook}_out.ipynb" -p HPO_ITER 1 -k my_env_kernel 
        
    - name: Compile modeling_drug_response
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        notebook='examples/tutorials/modeling_drug_response'
        papermill "${notebook}.ipynb" "${notebook}_out.ipynb" -p HPO_ITER 1 -k my_env_kernel
        
    - name: Compile survival_subtypes_LGG_GBM
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        notebook='examples/tutorials/survival_subtypes_LGG_GBM'
        papermill "${notebook}.ipynb" "${notebook}_out.ipynb" -p HPO_ITER 1 -k my_env_kernel

    - name: Compile scrnaseq_bonemarrow
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        notebook='examples/tutorials/scrnaseq_bonemarrow'
        papermill "${notebook}.ipynb" "${notebook}_out.ipynb" -p HPO_ITER 1 -k my_env_kernel
        
    - name: Compile neuroblastoma_data_integration
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        notebook='examples/tutorials/neuroblastoma_data_integration' 
        papermill "${notebook}.ipynb" "${notebook}_out.ipynb" -p HPO_ITER 1 -k my_env_kernel

    - name: Compile unsupervised_analysis_single_cell
      shell: bash -l {0}
      run: |
        source ~/.venv/my_env/bin/activate
        notebook='examples/tutorials/unsupervised_analysis_single_cell'
        papermill "${notebook}.ipynb" "${notebook}_out.ipynb" -p HPO_ITER 1 -k my_env_kernel 
