name: Check Tutorials

on:
  workflow_dispatch: # This line enables manual triggering of the workflow
  schedule:
    # Runs at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'

jobs:
  check_tutorials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.9'

    - name: Cache Conda environment
      uses: actions/cache@v2
      with:
        path: ~/miniconda/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('spec-file.txt') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Create environment with dependencies
      shell: bash -l {0}
      run: |
        conda create --name my_env --file spec-file.txt
        conda activate my_env

    - name: Install package from source
      shell: bash -l {0}
      run: |
        conda activate my_env
        pip install -e .

    - name: Install additional dependencies
      shell: bash -l {0}
      run: |
        conda activate my_env
        pip install torch_geometric nbconvert nbclient papermill
    
    - name: Install Jupyter Kernel
      shell: bash -l {0}
      run: |
        conda activate my_env
        pip install ipykernel
        python -m ipykernel install --user --name my_env_kernel --display-name "my_env_kernel"

    - name: Compile brca_subtypes.ipynb
      shell: bash -l {0}
      run: |
        conda activate my_env
        notebook='examples/tutorials/brca_subtypes.ipynb'
        papermill "${notebook}" "${notebook}_out" -p HPO_ITER 1 -k my_env_kernel 
        
    - name: Compile modeling_drug_response
      shell: bash -l {0}
      run: |
        conda activate my_env
        notebook='examples/tutorials/modeling_drug_response.ipynb'
        papermill "${notebook}" "${notebook}_out" -p HPO_ITER 1 -k my_env_kernel
        
    - name: Compile survival_subtypes_LGG_GBM
      shell: bash -l {0}
      run: |
        conda activate my_env
        notebook='examples/tutorials/survival_subtypes_LGG_GBM.ipynb'
        papermill "${notebook}" "${notebook}_out" -p HPO_ITER 1 -k my_env_kernel

    - name: Compile scrnaseq_bonemarrow
      shell: bash -l {0}
      run: |
        conda activate my_env
        notebook='examples/tutorials/scrnaseq_bonemarrow.ipynb'
        papermill "${notebook}" "${notebook}_out" -p HPO_ITER 1 neuroblastoma_data_integration -k my_env_kernel
        
    - name: Compile neuroblastoma_data_integration
      shell: bash -l {0}
      run: |
        conda activate my_env
        notebook='examples/tutorials/neuroblastoma_data_integration.ipynb' -k my_env_kernel
        papermill "${notebook}" "${notebook}_out" -p HPO_ITER 1
